### ISSUE TITLE
Can't excavate or tunnel using Turtle

### ISSUE THREAD

**Issue by lucaargolo** [Shrimpstress/cc-tweaked-fabric#1]
Minecraft: 1.16.2
CC: Tweaked: 1.19.1
Fabric API: 0.19.0+build398-1.16

Hi, I can't excavate or tunnel using the Diamond Pickaxe Turtle
[Here you can see a step by step on how to reproduce this.](https://i.imgur.com/ObqVCTM.mp4)

**Comment by Shrimpstress** [comment]
Looking into it now.

**Comment by Shrimpstress** [comment]
Fixed in cc72e1c. Will put on Fibercraft in a bit.
