### ISSUE TITLE
Buckets being consumed by turtle.place

### ISSUE THREAD

**Issue by prozacgod** [Shrimpstress/cc-tweaked-fabric#10]
- Minecraft version : 16.2
 - CC: Tweaked version : 1.91.1
 - Detailed reproduction steps: 

Turtle over lava, single bucket in slot 1 of turtle, run lua and "turtle.placeDown()"

The bucket gets lost, this issue seems to have also existed in the cc:tweaked github issue tracker.

https://github.com/SquidDev-CC/CC-Tweaked/issues/530

I tried this in both ssp, smp

**Comment by Ueaj-Kerman** [comment]
fixed in release on curseforge
