### ISSUE TITLE
pocket computers crashing game

### ISSUE THREAD

**Issue by FELIX090915** [Shrimpstress/cc-tweaked-fabric#13]
# Pocket computers crash the game 

- Detailed reproduction steps: When in creative mod grab any pocket computer and it will crash the game, the give command also crashes the game. And every time I open the world it crashes

 - Minecraft version: 1.16.2
 - CC: version 1.91.1
[Crash log.txt](https://github.com/Zundrel/cc-tweaked-fabric/files/5322686/Crash.log.txt)

The other mods i have installed are:
- Carpet and carpet extra
- Fabric Api
- Litematica
- MaLiLib
- Shulker Box Tultips
- World Edit

**Comment by Ueaj-Kerman** [comment]
what

**Comment by vini2003** [comment]
blame half

**Comment by Ueaj-Kerman** [comment]
irit
