### ISSUE TITLE
Can't break any CCR blocks

### ISSUE THREAD

**Issue by Nixill** [Shrimpstress/cc-tweaked-fabric#19]
As the title says, I can't break any blocks at all. They appear to be broken on the client but nothing drops and you still can't move into that space. Tested in multiplayer and singleplayer with a modpack, and in singleplayer by itself.

## Useful information to include:
 - Minecraft version: 1.16.1
 - CC: Tweaked version: "fixes buckets being eaten by turtles" (1.91.2)
 - [Log file](https://gist.github.com/ShadowFoxNixill/98226b2933013ccc9bbf6be2922c310a#file-latest-log-L662) - please pardon lines 40-589 (datapack recipe errors because making it error is the only way to remove a recipe from the game).

### Reproduction steps:
1. Make creative world
2. Place computer
3. Break computer
4. Attempt to walk into space the computer occupied (expected result: walk into that space / actual result: rubberbanded out)
5. Attempt to place a different block there (expected result: that block is now there / actual result: a computer is now there)

**Comment by Nixill** [comment]
I just confirmed that this bug is exclusive to 1.16.1. If it's a won'tfix for that reason, I understand - I'm already looking into upgrading my server to .3 myself, but a few mods we use haven't been updated yet.

I do recommend, at the very least, removing 1.16 and 1.16.1 from the list of versions [the latest file](https://www.curseforge.com/minecraft/mc-mods/cc-restitched/files/3057829) supports.

**Comment by Shrimpstress** [comment]
Yeah this likely isn't something that we'll look into fixing, the mod was never designed for 1.16.1. We always targeted 1.16.2 from the get-go. That being said, I'll remove 1.16.1 from the supported versions on CF for now. Thankfully we're at a point now where 1.16.3 is compatible with basically everything that was holding people back on 1.16.1, so the good news is it should be a fairly easy move for your server.

**Comment by Nixill** [comment]
Agreed, I just tested what works in .3 and we're honestly losing little enough that I'm ready to update as soon as everyone's available to do so.

Anyway, I'll go ahead and close the issue with this comment.
