### ISSUE TITLE
turtle disappears when mined by another turtle

### ISSUE THREAD

**Issue by rudrakshm** [Shrimpstress/cc-tweaked-fabric#25]
minecraft version:fabric 1.16.4
cc:T version:1.91.2

if one turtle digs another, the latter does not go into the inventory or fall on the ground.it just  disappears

**Comment by techninja1008** [comment]
Can confirm this also happens with normal and advanced computers as well, but not any other blocks in the mod.

**Comment by Shrimpstress** [comment]
This should be fixed in the next release.
