### ISSUE TITLE
Inventories cannot be "wrapped"

### ISSUE THREAD

**Issue by waidesoper** [Shrimpstress/cc-tweaked-fabric#41]
I've checked the open issues and I was surprised to see this one hasn't been reported.

In CC:T the modem block will detect inventories on connected sides and expose their methods to Lua. This also happens when using a turtle; the inventories are not showing up.

MC Version 1.16.4
CC:R version 1.91.2

To reproduce:
Place a modem block next to a chest
right click the modem
should show a message "Chest_0 attached to network" instead does nothing

OR

Place a turtle next to a chest
enter the Lua console
type: peripheral.getNames() and press enter
should show a table with the chest in it, instead returns nil

**Comment by Merith-TK** [comment]
This repo is unmaintained, please look at #45 and [CC: Restitched](/Merith-TK/cc-restitched)

**Comment by waidesoper** [comment]
I forgot I lodged this.
