### ISSUE TITLE
Will Not Load a World

### ISSUE THREAD

**Issue by ghost** [Shrimpstress/cc-tweaked-fabric#7]
CC:T 1.91.1 (the release from a couple hours ago) on 1.16.2 with Loader 0.9.3 build 207 and API 0.20.1 build 401 will not generate a world or load an existing one.
https://paste.ee/p/CP3UA
 - 1.16.2
 - CC: Tweaked version 1.91.1

**Comment by ghost** [comment]
I forgot to mention that this occurs with Java 8 and 14. The log for 14 is in the original report, this is the log for 8: https://paste.ee/p/gSEsc

**Comment by Ueaj-Kerman** [comment]
I think that's my fault, will fix ina bit

**Comment by Ueaj-Kerman** [comment]
ok now just wait for zundrel to push a released, fixed
https://github.com/Zundrel/cc-tweaked-fabric/commit/e1b8ac1f84e56dc837b8c7d7ce59cf7af7867abe
