### ISSUE TITLE
Crash when holding a pocket computer

### ISSUE THREAD

**Issue by Desynq** [Shrimpstress/cc-tweaked-fabric#8]
[crash-2020-09-11_19.58.43-client.txt](https://github.com/Zundrel/cc-tweaked-fabric/files/5211909/crash-2020-09-11_19.58.43-client.txt)

Crash is caused by holding a pocket computer (Singeplayer and Multiplayer)
Using the latest version of CC available for 1.16.2 on curseforge. 
No other mods apart from the latest version of Fabric API are present.
Using latest version of Fabric for 1.16.2

**Comment by Ueaj-Kerman** [comment]
can u send the log and not the crash

**Comment by Desynq** [comment]
> can u send the log and not the crash

Not to sound stupid but how do I find the log?

**Comment by Ueaj-Kerman** [comment]
in the `logs` folder

**Comment by crabdancing** [comment]
I just encountered this problem too. Here's the [log](https://paste.ee/p/jcfmV). I just crafted it and the game immediately crashed. I loaded it back up, and it crashed before I could even do anything.

**Comment by Ueaj-Kerman** [comment]
intresting will check

**Comment by Ueaj-Kerman** [comment]
fixed, release published https://github.com/Zundrel/cc-tweaked-fabric/releases/tag/v1.19.2
