### ISSUE TITLE
Turtles should retain execution state when chunk unloads

### ISSUE THREAD

**Issue by crabdancing** [Shrimpstress/cc-tweaked-fabric#9]
Wasn't sure if this was intended behavior or not, but it seems unintended so I'm marking it as a bug.

I noticed some strange behavior from my turtles, and played around with CC 1.16.2-1.91.2 in a creative world. It turns out that whenever a chunk is unloaded and reloaded, all computers & turtles lose their execution state and go back to idling with the shell. This happens even when I just have the CC and Fabric API mods. Am using Minecraft 1.16.3 with Fabric API 0.20.2+build.402-1.16 and Fabric Loader 0.9.3+build.207.

**Comment by Ueaj-Kerman** [comment]
did you check if there's an issue for this on the main repo

**Comment by crabdancing** [comment]
@Devan-Kerman I wasn't aware that this wasn't the main repo at this point. I just got here through the link on Fabric. Is upstream still being maintained?

Edit: or are you talking about the Forge version? I'm wasn't sure if you're trying to maintain code parity with that version, or just feature set.

**Comment by Ueaj-Kerman** [comment]
I mean the forge repo, this repo is a direct port of that

**Comment by crabdancing** [comment]
There is [this](https://github.com/SquidDev-CC/CC-Tweaked/issues/535) issue. I guess if this codebase is dependent on that core, I should close this issue and we wait until upstream implements.

**Comment by Ueaj-Kerman** [comment]
I wish there was a way to track other issues on gh
